### ISSUE TITLE
Support a pharcc config file

### ISSUE THREAD

**Issue by cbednarski** [cbednarski/pharcc#1]
Filename `.pharcc` or `pharcc.yml`

``` yml
include:
  - src/
  - vendor/
exclude:
  - *Test.php
main: bin/spark
```
